version: '3.8'
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - "5173:5173"
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: Dockerfile-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/mealMatters
      - PORT=5000
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: