# Dockerfile-frontend

# Use Node.js as the base image
FROM node:20

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY client/package*.json ./

# Install dependencies
RUN npm install

# Copy the client directory
COPY client/ .

# Expose the frontend port
EXPOSE 5173

# Command to run the app
CMD ["npm", "run", "dev"]